In [5]:
x=1

I just assigned x = 1!

In [6]:
xyxyx =10

In [7]:
xyxyx

10

**Strings**

In [8]:
name = 'Imogen'

In [9]:
name

'Imogen'

In [10]:
type(name)

str

In [13]:
name[2]

'o'

In [14]:
name[2] = 'y'

TypeError: 'str' object does not support item assignment

In [15]:
name = name[0:2] +'y' + name[3:]

In [16]:
name

'Imygen'

**Floats**

In [17]:
x = 0.34

In [18]:
type(x)

float

**Integes**

In [19]:
i =1

In [20]:
type(i)

int

**Boolean**

In [21]:
ans = True

In [22]:
type(ans)

bool

### Data Structures

In [23]:
squares = [1, 5, 9, 16]

In [24]:
squares

[1, 5, 9, 16]

In [25]:
squares[1] = 4

In [26]:
squares

[1, 4, 9, 16]

In [32]:
squares[-1::-1]

[16, 9, 4, 1]

In [33]:
squares.append(25)
squares

[1, 4, 9, 16, 25]

In [34]:
squares = squares + [36]
squares

[1, 4, 9, 16, 25, 36]

In [36]:
A = [[1, 2, 3], [4, 5, 6]]
A

[[1, 2, 3], [4, 5, 6]]

In [39]:
A[1][1]

5

In [40]:
A[1][1] ='g'

In [41]:
A

[[1, 2, 3], [4, 'g', 6]]

In [42]:
type(A)

list

### Tuple

In [43]:
B = (1, 2, 3)

In [44]:
B[1]

2

In [45]:
B[1] = 3

TypeError: 'tuple' object does not support item assignment

### Sets

In [46]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
basket

{'apple', 'banana', 'orange', 'pear'}

In [48]:
'kiwi' in basket

False

### Dict

In [51]:
cars = {'Prius':'Toyota', 'Volt': 'Chevy', 'Model 3': 'Tesla'}
cars['Prius']

'Toyota'

# Numpy

In [54]:
import numpy as np

In [82]:
a = np.array([[1, 2, 3,4], [4,5,6,3]])

In [83]:
a

array([[1, 2, 3, 4],
       [4, 5, 6, 3]])

In [62]:
a[1,0]

4

In [63]:
a[1,1] = 'g'

ValueError: invalid literal for int() with base 10: 'g'

In [64]:
a[1,1] = 0.1

In [65]:
a

array([[1, 2, 3],
       [4, 0, 6]])

In [66]:
type(a)

numpy.ndarray

In [68]:
b = np.array([[0.1, 0.3], [1, 2]])

In [69]:
b

array([[0.1, 0.3],
       [1. , 2. ]])

In [70]:
type(b)

numpy.ndarray

In [86]:
a

array([[1, 2, 3, 4],
       [4, 5, 6, 3]])

In [87]:
a[:,::2]

array([[1, 3],
       [4, 6]])

# Pandas

In [88]:
fruit_list = {'fruit':['apple', 'banana', 'orange', 'kiwi'],
             'color':['red', 'yellow', 'orange','brown'],
             'weight':[70, 92, 200, 50]}
fruit_list

{'fruit': ['apple', 'banana', 'orange', 'kiwi'],
 'color': ['red', 'yellow', 'orange', 'brown'],
 'weight': [70, 92, 200, 50]}

In [90]:
fruit_list['weight']

[70, 92, 200, 50]

In [91]:
import pandas as pd
fruit_df = pd.DataFrame(data = fruit_list)

In [92]:
fruit_df

fruit   color  weight
0   apple     red      70
1  banana  yellow      92
2  orange  orange     200
3    kiwi   brown      50

In [93]:
type(fruit_df)

pandas.core.frame.DataFrame

In [94]:
fruit_df['fruit']

0     apple
1    banana
2    orange
3      kiwi
Name: fruit, dtype: object

In [95]:
type(fruit_df['fruit'])

pandas.core.series.Series

## Getting data out

In [98]:
fruit_df['weight'][0]

70

In [99]:
fruit_df.loc[0,'weight']

70

In [102]:
fruit_df.iloc[0,2]

70

In [105]:
fruit_df.iloc[:,0:1]

fruit
0   apple
1  banana
2  orange
3    kiwi

In [106]:
!ls

'~$03 Pandas.pptx'	     "Duncan's Lecture 3 in class workbook.ipynb"
'03 Pandas.pptx'	     'Lecture 3 Notebook.html'
 CAISO_2017to2018.csv	     'Lecture 3 Notebook.ipynb'
 CAISO_2017to2018_stack.csv  'My Lecture 3 in class workbook.ipynb'
 dataframe_anatomy.png


In [107]:
import os
os.listdir()

['.ipynb_checkpoints',
 'CAISO_2017to2018_stack.csv',
 "Duncan's Lecture 3 in class workbook.ipynb",
 '~$03 Pandas.pptx',
 'Lecture 3 Notebook.ipynb',
 '03 Pandas.pptx',
 'dataframe_anatomy.png',
 'Lecture 3 Notebook.html',
 'CAISO_2017to2018.csv',
 'My Lecture 3 in class workbook.ipynb']

In [108]:
caiso_df = pd.read_csv('CAISO_2017to2018.csv')
caiso_df.head()

Unnamed: 0  GEOTHERMAL  BIOMASS  BIOGAS  SMALL HYDRO  WIND TOTAL  \
0  2017-08-29 00:00:00        1181      340     156          324        1551   
1  2017-08-29 01:00:00        1182      338     156          326        1556   
2  2017-08-29 02:00:00        1183      337     156          337        1325   
3  2017-08-29 03:00:00        1185      339     156          313        1158   
4  2017-08-29 04:00:00        1190      344     156          320        1209   

   SOLAR PV  SOLAR THERMAL  
0         0              0  
1         0              0  
2         0              0  
3         0              0  
4         0              0

In [109]:
caiso_df['GEOTHERMAL']

0       1181
1       1182
2       1183
3       1185
4       1190
5       1194
6       1196
7       1194
8       1187
9       1189
10      1186
11      1180
12      1177
13      1175
14      1172
15      1172
16      1173
17      1175
18      1180
19      1190
20      1197
21      1200
22      1205
23      1207
24      1208
25      1209
26      1210
27      1209
28      1205
29      1209
        ... 
8730     959
8731     967
8732     969
8733     970
8734     972
8735     975
8736     976
8737     977
8738     979
8739     981
8740     970
8741     976
8742     976
8743     975
8744     973
8745     970
8746     967
8747     944
8748     936
8749     934
8750     933
8751     933
8752     934
8753     934
8754     955
8755     962
8756     967
8757     972
8758     975
8759     977
Name: GEOTHERMAL, Length: 8760, dtype: int64

In [111]:
caiso_df = pd.read_csv('CAISO_2017to2018.csv', index_col = 0)
caiso_df.loc['2017-08-29 09:00:00','GEOTHERMAL']

1189

In [112]:
caiso_stacked_df = pd.read_csv('CAISO_2017to2018_stack.csv', index_col = 0)

In [114]:
caiso_stacked_df.head()

Source   MWh
2017-08-29 00:00:00   GEOTHERMAL  1181
2017-08-29 00:00:00      BIOMASS   340
2017-08-29 00:00:00       BIOGAS   156
2017-08-29 00:00:00  SMALL HYDRO   324
2017-08-29 00:00:00   WIND TOTAL  1551

In [118]:
list = caiso_stacked_df['Source'] == 'WIND TOTAL'
list.head()

2017-08-29 00:00:00    False
2017-08-29 00:00:00    False
2017-08-29 00:00:00    False
2017-08-29 00:00:00    False
2017-08-29 00:00:00     True
Name: Source, dtype: bool

In [122]:
caiso_stacked_df.loc[list,'MWh']

2017-08-29 00:00:00    1551
2017-08-29 01:00:00    1556
2017-08-29 02:00:00    1325
2017-08-29 03:00:00    1158
2017-08-29 04:00:00    1209
2017-08-29 05:00:00    1209
2017-08-29 06:00:00    1126
2017-08-29 07:00:00    1164
2017-08-29 08:00:00     903
2017-08-29 09:00:00     711
2017-08-29 10:00:00     728
2017-08-29 11:00:00     709
2017-08-29 12:00:00     726
2017-08-29 13:00:00     823
2017-08-29 14:00:00    1100
2017-08-29 15:00:00    1467
2017-08-29 16:00:00    1941
2017-08-29 17:00:00    1430
2017-08-29 18:00:00    1562
2017-08-29 19:00:00    1590
2017-08-29 20:00:00    1855
2017-08-29 21:00:00    1905
2017-08-29 22:00:00    1841
2017-08-29 23:00:00    1915
2017-08-30 00:00:00    2256
2017-08-30 01:00:00    2352
2017-08-30 02:00:00    2238
2017-08-30 03:00:00    2151
2017-08-30 04:00:00    2048
2017-08-30 05:00:00    1806
                       ... 
2018-08-27 18:00:00    3200
2018-08-27 19:00:00    2904
2018-08-27 20:00:00    2750
2018-08-27 21:00:00    2697
2018-08-27 22:00:00 